### ISSUE TITLE
需要先替换默认的登陆壁纸才能使用这个脚本

### ISSUE THREAD

**Issue by docdruid** [kkkgo/DSM_Login_BingWallpaper#1]
需要先替换默认的登陆壁纸才能使用这个脚本
在设置->主题->勾选一个任意一张预选壁纸才能启用这个脚本.

普通NAS用户,哪怕是Administrator用户组的也没有权限完成这个脚本任务.

最好更新下教程.

**Comment by kkkgo** [comment]
脚本已经更新，现无需先替换默认的登陆壁纸。可以测试。
