### ISSUE TITLE
在chrome上登录  登录背景被浏览器缓存无法显示新图片

### ISSUE THREAD

**Issue by He-Xun** [kkkgo/DSM_Login_BingWallpaper#10]
我在登录页的html的head里加入了
\<meta http-equiv="Cache-Control" content="no-cache">
\<meta http-equiv="Pragma" content="no-cache">
\<meta http-equiv="Expires" content="-1">'''
还是不起作用  请问有什么方式解决这个问题么

**Comment by kkkgo** [comment]
1、使用脚本前请设置任意自定义壁纸为背景
2、使用最新脚本
