### ISSUE TITLE
请问怎么恢复成默认的桌面

### ISSUE THREAD

**Issue by Zeke0n** [kkkgo/DSM_Login_BingWallpaper#12]
脚本任务删了以后个人桌面还是bing的，重新设置壁纸也没用。

**Comment by kkkgo** [comment]
脚本是是直接覆盖原壁纸的
可以把默认壁纸放在指定目录然后修改脚本覆盖掉

**Comment by Zeke0n** [comment]
已经执行过脚本的没办法恢复了对吗 😂

**Comment by kkkgo** [comment]
把第8行的tmpfile=/tmp/$date"_bing.jpg"  
改成你想要替换的壁纸的路径即可。
