### ISSUE TITLE
壁纸不能全屏

### ISSUE THREAD

**Issue by WeiKKJ** [kkkgo/DSM_Login_BingWallpaper#13]
浏览器最大化后，壁纸不跟着全屏啊。
![image](https://user-images.githubusercontent.com/50602973/61632689-0e973680-acc0-11e9-9bb7-79e3737305e4.png)

**Comment by tanst** [comment]
对，有这个问题，浏览器分辨率大于1080会出现白边，登录进去正常，对比了一下，少了一个样式：
`background-size: cover;`，但是我不知道群晖改哪个文件，囧~

**Comment by kkkgo** [comment]
1、使用脚本前请设置任意自定义壁纸为背景
2、使用最新脚本

**Comment by tanst** [comment]
无效啊，新脚本连背景都不换了

**Comment by kkkgo** [comment]
使用脚本前请设置任意自定义壁纸为背景

**Comment by tanst** [comment]
![image](https://user-images.githubusercontent.com/4686616/74908427-c58f9800-53f0-11ea-8e25-4590f5570024.png)
自定义了背景，然后运行脚本，标题是改了，但是图片没变（缓存已清）

**Comment by kkkgo** [comment]
什么版本，DSM 6.2.2-24922 Update 4没有问题，你自定义了背景之后背景有变化么

**Comment by tanst** [comment]
一样的版本，自定义了背景之后背景变成自定义的图片，然后运行脚本，背景还是自定义的图片

**Comment by kkkgo** [comment]
你选择自带Wallpaper3 然后再运行脚本看看

**Comment by tanst** [comment]
恩，我把自定义改成系统自带的，再运行脚本，可以了
