### ISSUE TITLE
脚本更换的壁纸不自动更新，希望解决。

### ISSUE THREAD

**Issue by kerblion** [kkkgo/DSM_Login_BingWallpaper#14]
脚本更换的壁纸不自动更新，希望解决。

**Comment by Vtrois** [comment]
最新版本的DSM存放自定义背景图片是在 /usr/syno/etc/login_image 里 background*.jpg 命名，修改一下路径即可

**Comment by kkkgo** [comment]
1、使用脚本前请设置任意自定义壁纸为背景
2、检查网络问题
