### ISSUE TITLE
如何更改桌面壁纸

### ISSUE THREAD

**Issue by WeiKKJ** [kkkgo/DSM_Login_BingWallpaper#16]
老师，我用这个脚本，登录界面的壁纸更改没问题，可是登陆进系统之后，桌面的壁纸还是原来系统默认的，这个能改吗？

**Comment by kkkgo** [comment]
修改用户壁纸非全局功能，除非替换系统文件或者指定用户路径才可以实现，加上这个功能可能用起来过于复杂，有人提交过pr，你可以参考：
https://github.com/kkkgo/DSM_Login_BingWallpaper/pull/15/files
