### ISSUE TITLE
群晖7.0出来了，老哥有没有想法更新下脚本？

### ISSUE THREAD

**Issue by skypjsfly** [kkkgo/DSM_Login_BingWallpaper#17]
更换登录页面壁纸的正常，但是更换桌面壁纸失效了

**Comment by aufwies** [comment]
you only need to modify the file path.I will post PR to update this script.

**Comment by skypjsfly** [comment]
> you only need to modify the file path.I will post PR to update this script.

I have tried ，but it does not work

**Comment by virtualvmw** [comment]
这个脚本不能用了，提示图片打开失败。通过保存位置查看图片，名称变成_bing.jp的样子了。

**Comment by kkkgo** [comment]
因为我几年前更换了威联通，因此没有更新，现在已经使用虚拟机测试更新脚本，欢迎测试。   
Because I replaced QNAP a few years ago, update stop. now I  used the vmware to code the script, welcome to test.
