### ISSUE TITLE
发现了两个问题，还有一个帮助请求

### ISSUE THREAD

**Issue by X-Tor** [kkkgo/DSM_Login_BingWallpaper#2]
$$$
您好，我在我的群晖中试了一下您的代码，发现了两个问题，如下：
$$$
1、您代码中“story=$(curl -s https://cn.bing.com/cnhp/coverstory)”中的网址，curl -s中返回的信息为 跳转到“https://www4.bing.com/cnhp/coverstory”，Po不到任何信息，将以上代码改为“story=$(curl -s https://www4.bing.com/cnhp/coverstory)”才能Po到信息。
$$$
2、您的代码中提到

sed -i s/login_background_customize=.*/login_background_customize=\"yes\"/g /etc/synoinfo.conf
这个应该是开启用户自定义壁纸，但是没有作用，还是得手动开启一下。

可实际测试中，还是要点击右上角头像进行开启自定义壁纸操作。
$$$
另，请求您的帮助，问题如下：

我尝试获取"attribute"和"para1"两个字段然后合并替换/etc/synoinfo.conf中的login_welcome_msg=，但是运行后为空白。

例如，现在返回值为

"title":"跃动的蒙德里安","attribute":"美国，纽约","para1":"这段太长省略"

我想让login_welcome_msg=美国，纽约--这段太长省略

但是/etc/synoinfo.conf中会变成login_welcome_msg=“”
$$$
我的DSM版本是DSM 6.2-23511 该版本为测试版。
我的电子邮箱是：460685244@qq.com 希望通过电子邮件与您交流。

**Comment by kkkgo** [comment]
现在才刚看到这个issue，第1个问题我这里运行没问题，目前是DSM 6.1.7-15284的DS1517+；
![curl](https://user-images.githubusercontent.com/4530897/40646859-02b3347a-635d-11e8-866f-234bae822040.png)
不过www4bing那个我测试也能用，所以我待会把这个链接改改；
第二个问题上次已经修正了，大概是你提出这个issue之前还是之后的时间传了个新的；
第三个问题，我写个参考你测试下：
story=$(curl -s https://www4.bing.com/cnhp/coverstory)
attribute=$(echo $story|grep -Po 'attribute[" :]+\K[^"]+')
para1=$(echo $story|grep -Po 'para1":"\K[^"]+')
welmsg=$attribute"--"$para1
sed -i s/login_welcome_msg=.*/login_welcome_msg=\"$welmsg\"/g /etc/synoinfo.conf
