### ISSUE TITLE
关于Photo Station无法自动索引文件

### ISSUE THREAD

**Issue by MeowPerth** [kkkgo/DSM_Login_BingWallpaper#21]
目前发现一个情况，将脚本和Photo station结合使用时，每次通过脚本保存到Photo station的相册目录地址中，无法让Photo station索引到这个图片。但是不通过ssh，给文件重新命名一下就能索引到了。有办法解决这个问题么

**Comment by kkkgo** [comment]
因为我几年前更换了威联通，因此没有更新，现在已经使用虚拟机测试更新脚本，欢迎测试。
Because I replaced QNAP a few years ago, update stop. now I used the vmware to code the script, welcome to test.

**Comment by kkkgo** [comment]
最新版的DSM7.0似乎是重构成Synology Photos，测试可以正常索引。
![image.png](https://s2.loli.net/2022/08/24/rw2DaznWiI54yUQ.png)

**Comment by MrEleven** [comment]
我更严重，重命名都不一定能被索引到，有好的解决办法吗？

**Comment by kkkgo** [comment]
> 我更严重，重命名都不一定能被索引到，有好的解决办法吗？

是Synology Photos么

**Comment by MrEleven** [comment]
是的，我写了个脚本每天定时爬取抖音的视频，但是跑完脚本就是不会被Synology Photos自动索引。大部分情况下移动下位置或者通过mv命令改名字也没用。偶尔mv了之后会被索引。

**Comment by kkkgo** [comment]
> 是的，我写了个脚本每天定时爬取抖音的视频，但是跑完脚本就是不会被Synology Photos自动索引。大部分情况下移动下位置或者通过mv命令改名字也没用。偶尔mv了之后会被索引。

请问是这个脚本的壁纸无法索引还是你的视频无法索引

**Comment by MrEleven** [comment]
是我的视频无法索引。我今天问了群晖的技术支持，Synology Photos确实不支持通过命令或者程序创建的文件的索引。

**Comment by standin000** [comment]
> 是我的视频无法索引。我今天问了群晖的技术支持，Synology Photos确实不支持通过命令或者程序创建的文件的索引。

试试用file station重命名该视频文件夹
