### ISSUE TITLE
cp: target '.jpg' is not a directory

### ISSUE THREAD

**Issue by kirito-0** [kkkgo/DSM_Login_BingWallpaper#24]
设置保存文件夹路径无法保存
output.log内容 cp: target '.jpg' is not a directory
有建立共用资料夹

**Comment by ghost** [comment]
Same here, seems to have problems with the long filename including blanks?

Aufgabe: Daily Bing Wallpapers
Start: Sat, 04 Jun 2022 09:46:27 GMT
Ende: Sat, 04 Jun 2022 09:46:27 GMT
Aktueller Status: 0 (Normal)
Standardausgabe/Fehler:
cp: target 'Wanderwege-Blick auf den Banner Peak vom Thousand Islands Pass, Ansel Adams Wilderness, Kalifornien, USA .jpg' is not a directory

**Comment by kirito-0** [comment]
> Same here, seems to have problems with the long filename including blanks?
> 
> Aufgabe: Daily Bing Wallpapers Start: Sat, 04 Jun 2022 09:46:27 GMT Ende: Sat, 04 Jun 2022 09:46:27 GMT Aktueller Status: 0 (Normal) Standardausgabe/Fehler: cp: target 'Wanderwege-Blick auf den Banner Peak vom Thousand Islands Pass, Ansel Adams Wilderness, Kalifornien, USA .jpg' is not a directory

Are you having the same error problem? Can't save pictures to the directory?

**Comment by ghost** [comment]
> Are you having the same error problem? Can't save pictures to the directory?

Exactly. The path is correct but there doesn't seem to be any picture placed in the directory.

**Comment by mada199122** [comment]
I'm having the same problem
`cp: target 'mare-Sentieri aggrovigliati di via Krupp, Capri .jpg' is not a directory`

**Comment by kkkgo** [comment]
因为我几年前更换了威联通，因此没有更新，现在已经使用虚拟机测试更新脚本，欢迎测试。
Because I replaced QNAP a few years ago, update stop. now I used the vmware to code the script, welcome to test.
