### ISSUE TITLE
老哥脚本不能用了

### ISSUE THREAD

**Issue by virtualvmw** [kkkgo/DSM_Login_BingWallpaper#25]
升了DSM7.0后一直在用呢，突然有一天就不行了。下载的文件变成了_bing.jpg，

**Comment by kkkgo** [comment]
因为我几年前更换了威联通，因此没有更新，现在已经使用虚拟机测试更新脚本，欢迎测试。
Because I replaced QNAP a few years ago, update stop. now I used the vmware to code the script, welcome to test.
