### ISSUE TITLE
DSM6 无法保存壁纸解决方案

### ISSUE THREAD

**Issue by Rocky-CN** [kkkgo/DSM_Login_BingWallpaper#26]
### 问题描述：
2022年8月20日，在已经去掉第2行的注释，定义了savepath的情况下，执行脚本无法保存壁纸。
### 知乎上找到的解决方案    [源网址](https://zhuanlan.zhihu.com/p/395577125)：
将代码的第29行的$word变量加上双引号
原代码29行为
`cp -f $tmpfile $savepath/$date@$title-$word.jpg`
替换为以下代码：
`cp -f $tmpfile $savepath/$date@$title-"$word".jpg`

### 2022年8月22日更新
将29行的文件名减少到只有日期，仍然无法保存，所以**原因不是文件名过长**。代码如下：
`cp -f $tmpfile $savepath/$date.jpg`
加上双引号后，可以正常保存。替换代码如下：
`cp -f $tmpfile "$savepath/$date.jpg"`

希望作者更新一下。

**Comment by kkkgo** [comment]
因为我几年前更换了威联通，因此没有更新，现在已经使用虚拟机测试更新脚本，欢迎测试。
Because I replaced QNAP a few years ago, update stop. now I used the vmware to code the script, welcome to test.
