### ISSUE TITLE
脚本执行错误

### ISSUE THREAD

**Issue by smallmj** [kkkgo/DSM_Login_BingWallpaper#3]
今天运行脚本发现壁纸没有换，文字也没有抓取完全，设置给邮件发了运行报告：
任务计划程序已完成计划任务。

任务： Get_Bingwallpaper
开始时间： Thu, 10 Jan 2019 11:24:29 GMT
结束时间： Thu, 10 Jan 2019 11:24:31 GMT
当前状态： 0 (正常)
标准输出/错误：
login_background_customize="yes"
login_welcome_title="神秘之境"
sed: invalid option -- '3'
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...

  -n, --quiet, --silent
                 suppress automatic printing of pattern space
  -e script, --expression=script
                 add the script to the commands to be executed
  -f script-file, --file=script-file
                 add the contents of script-file to the commands to be executed
  --follow-symlinks
                 follow symlinks when processing in place
  -i[SUFFIX], --in-place[=SUFFIX]
                 edit files in place (makes backup if SUFFIX supplied)
  -l N, --line-length=N
                 specify the desired line-wrap length for the `l' command
  --posix
                 disable all GNU extensions.
  -r, --regexp-extended
                 use extended regular expressions in the script.
  -s, --separate
                 consider files as separate rather than as a single continuous
                 long stream.
  -u, --unbuffered
                 load minimal amounts of data from the input files and flush
                 the output buffers more often
  -z, --null-data
                 separate lines by NUL characters
      --help     display this help and exit
      --version  output version information and exit

If no -e, --expression, -f, or --file option is given, then the first
non-option argument is taken as the sed script to interpret.  All
remaining arguments are names of input files; if no input files are
specified, then the standard input is read.

不知道是哪里出了问题

**Comment by kkkgo** [comment]
试试新脚本
