### ISSUE TITLE
新版图片下载下来是0kb

### ISSUE THREAD

**Issue by xxzj990** [kkkgo/DSM_Login_BingWallpaper#7]
如题

**Comment by kkkgo** [comment]
壁纸更换是否成功？保存路径是否和Filestation一致？

**Comment by xxzj990** [comment]
> 壁纸更换是否成功？保存路径是否和Filestation一致？

壁纸更换成功，但是是纯白背景。
路径是好的，是这两天才出问题的，之前一直好着，可能是bing的url返回的东西变了，正则出来的图片URL不对。我不太懂正则

**Comment by xxzj990** [comment]
![微信截图_20190312090902](https://user-images.githubusercontent.com/5134154/54167845-a8470f80-44a6-11e9-88f9-97c8b5828b3c.png)

这个是3月10号之前的截图，都可以下下来，10号之后就开始下载的文件是0kb，我把0kb的文件删了。

或者是我DSM的问题？

**Comment by kkkgo** [comment]
文件大小是0kb，文件名有完整标题吗

**Comment by xxzj990** [comment]
> 文件大小是0kb，文件名有完整标题吗

有

**Comment by kkkgo** [comment]
那首页的欢迎语应该也没问题吧？

**Comment by xxzj990** [comment]
> 应该也没

是的

**Comment by xxzj990** [comment]
> 那首页的欢迎语应该也没问题吧？

登录背景和桌面背景都是纯白色。

**Comment by xxzj990** [comment]
![微信截图_20190312095056](https://user-images.githubusercontent.com/5134154/54169106-5c976480-44ac-11e9-9c92-41bc9003c9de.png)

刚刚跑了一下脚本

**Comment by xxzj990** [comment]
我测试了正则，好像没问题

**Comment by kkkgo** [comment]
>savepath="/home/ubuntu"
pic=$(wget -t 5 --no-check-certificate -qO- "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1")
echo $pic >$savepath/bing.log
link=$(echo https://www.bing.com$(echo $pic|sed 's/.\+"url"[:" ]\+//g'|sed 's/".\+//g'))
echo $link >>$savepath/bing.log
date=$(echo $pic|sed 's/.\+enddate[": ]\+//g'|grep -Eo 2[0-9]{7}|head -1)
tmpfile=/tmp/$date"_bing.jpg"
echo $tmpfile >>$savepath/bing.log
wget -t 5 --no-check-certificate $link -O $tmpfile -o $savepath/bing.log

执行这段脚本 会在savepath产生日志bing.log

**Comment by xxzj990** [comment]
> > savepath="/home/ubuntu"
> > pic=$(wget -t 5 --no-check-certificate -qO- "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1")
> > echo $pic >$savepath/bing.log
> > link=$(echo https://www.bing.com$(echo $pic|sed 's/.+"url"[:" ]+//g'|sed 's/".+//g'))
> > echo $link >>$savepath/bing.log
> > date=$(echo $pic|sed 's/.+enddate[": ]+//g'|grep -Eo 2[0-9]{7}|head -1)
> > tmpfile=/tmp/$date"_bing.jpg"
> > echo $tmpfile >>$savepath/bing.log
> > wget -t 5 --no-check-certificate $link -O $tmpfile -o $savepath/bing.log
> 
> 执行这段脚本 会在savepath产生日志bing.log

OK，我试试

**Comment by xxzj990** [comment]
> ```shell
> savepath="/volume1/wallpaper"
> pic=$(wget -t 5 --no-check-certificate -qO- "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1")
> if (echo $pic|grep -q enddate) then
> link=$(echo https://www.bing.com$(echo $pic|sed 's/.\+"url"[:" ]\+//g'|sed 's/".\+//g'))
> date=$(echo $pic|sed 's/.\+enddate[": ]\+//g'|grep -Eo 2[0-9]{7}|head -1)
> tmpfile=/tmp/$date"_bing.jpg"
> wget -t 5 --no-check-certificate $link -qO $tmpfile -o $savepath/bing.log
> echo $link >>$savepath/bing.log
> echo $date >>$savepath/bing.log
> echo $tmpfile >>$savepath/bing.log
> echo $pic >>$savepath/bing.log
> ```

没有生成日志。。我再看看

**Comment by kkkgo** [comment]
没日志的话跑下面这段试试。
```shell
savepath="/volume1/wallpaper"
pic=$(wget -t 5 --no-check-certificate -qO- "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1")
link=$(echo https://www.bing.com$(echo $pic|sed 's/.\+"url"[:" ]\+//g'|sed 's/".\+//g'))
date=$(echo $pic|sed 's/.\+enddate[": ]\+//g'|grep -Eo 2[0-9]{7}|head -1)
tmpfile=/tmp/$date"_bing.jpg"
touch $savepath/bing.log
wget -t 5 --no-check-certificate $link -O $tmpfile -o $savepath/bing.log
echo $link >>$savepath/bing.log
echo $date >>$savepath/bing.log
echo $tmpfile >>$savepath/bing.log
echo $pic >>$savepath/bing.log
```

**Comment by xxzj990** [comment]
> 没日志的话跑下面这段试试。
> 
> ```shell
> savepath="/volume1/wallpaper"
> pic=$(wget -t 5 --no-check-certificate -qO- "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1")
> link=$(echo https://www.bing.com$(echo $pic|sed 's/.\+"url"[:" ]\+//g'|sed 's/".\+//g'))
> date=$(echo $pic|sed 's/.\+enddate[": ]\+//g'|grep -Eo 2[0-9]{7}|head -1)
> tmpfile=/tmp/$date"_bing.jpg"
> touch $savepath/bing.log
> wget -t 5 --no-check-certificate $link -O $tmpfile -o $savepath/bing.log
> echo $link >>$savepath/bing.log
> echo $date >>$savepath/bing.log
> echo $tmpfile >>$savepath/bing.log
> echo $pic >>$savepath/bing.log
> ```

![微信截图_20190312104835](https://user-images.githubusercontent.com/5134154/54171183-73da5000-44b4-11e9-8de2-1893ce798303.png)

日志：
https://www.bing.com/th?id=OHR.SpainRioTinto_ZH-CN9632593185_1920x1080.jpg&rf=NorthMale_1920x1080.jpg&pid=hp
20190312
/tmp/20190312_bing.jpg
{"images":[{"startdate":"20190311","fullstartdate":"201903111600","enddate":"20190312","url":"/th?id=OHR.SpainRioTinto_ZH-CN9632593185_1920x1080.jpg&rf=NorthMale_1920x1080.jpg&pid=hp","urlbase":"/th?id=OHR.SpainRioTinto_ZH-CN9632593185","copyright":"力拓河，西班牙 (© Oscar Diez Martinez/Minden Pictures)","copyrightlink":"http://www.bing.com/search?q=%E5%8A%9B%E6%8B%93%E6%B2%B3&form=hpcapt&mkt=zh-cn","title":"","quiz":"/search?q=Bing+homepage+quiz&filters=WQOskey:%22HPQuiz_20190311_SpainRioTinto%22&FORM=HPQUIZ","wp":true,"hsh":"316a27d6311f3857e5bc961d7795ec11","drk":1,"top":1,"bot":1,"hs":[]}],"tooltips":{"loading":"正在加载...","previous":"上一个图像","next":"下一个图像","walle":"此图片不能下载用作壁纸。","walls":"下载今日美图。仅限用作桌面壁纸。"}}


好了，文件也下载下来了，应该是少个fi

**Comment by kkkgo** [comment]
我把if那行去掉了啊（已编辑，可能你手快复制了之前的）。。你还是跑上面那段看看。。

**Comment by xxzj990** [comment]
> 我把if那行去掉了啊（已编辑，可能你手快复制了之前的）。。你还是跑上面那段看看。。

> --2019-03-12 10:53:26--  https://www.bing.com/th?id=OHR.SpainRioTinto_ZH-CN9632593185_1920x1080.jpg&rf=NorthMale_1920x1080.jpg&pid=hp
Resolving www.bing.com... 202.89.233.100, 202.89.233.101
Connecting to www.bing.com|202.89.233.100|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 346085 (338K) [image/jpeg]
Saving to: '/tmp/20190312_bing.jpg'

     0K .......... .......... .......... .......... .......... 14% 1.07M 0s
    50K .......... .......... .......... .......... .......... 29% 2.07M 0s
   100K .......... .......... .......... .......... .......... 44% 12.5M 0s
   150K .......... .......... .......... .......... .......... 59% 2.40M 0s
   200K .......... .......... .......... .......... .......... 73% 12.5M 0s
   250K .......... .......... .......... .......... .......... 88% 2.46M 0s
   300K .......... .......... .......... .......              100% 14.7M=0.1s

2019-03-12 10:53:26 (2.75 MB/s) - '/tmp/20190312_bing.jpg' saved [346085/346085]

https://www.bing.com/th?id=OHR.SpainRioTinto_ZH-CN9632593185_1920x1080.jpg&rf=NorthMale_1920x1080.jpg&pid=hp
20190312
/tmp/20190312_bing.jpg
{"images":[{"startdate":"20190311","fullstartdate":"201903111600","enddate":"20190312","url":"/th?id=OHR.SpainRioTinto_ZH-CN9632593185_1920x1080.jpg&rf=NorthMale_1920x1080.jpg&pid=hp","urlbase":"/th?id=OHR.SpainRioTinto_ZH-CN9632593185","copyright":"力拓河，西班牙 (© Oscar Diez Martinez/Minden Pictures)","copyrightlink":"http://www.bing.com/search?q=%E5%8A%9B%E6%8B%93%E6%B2%B3&form=hpcapt&mkt=zh-cn","title":"","quiz":"/search?q=Bing+homepage+quiz&filters=WQOskey:%22HPQuiz_20190311_SpainRioTinto%22&FORM=HPQUIZ","wp":true,"hsh":"316a27d6311f3857e5bc961d7795ec11","drk":1,"top":1,"bot":1,"hs":[]}],"tooltips":{"loading":"正在加载...","previous":"上一个图像","next":"下一个图像","walle":"此图片不能下载用作壁纸。","walls":"下载今日美图。仅限用作桌面壁纸。"}}

**Comment by kkkgo** [comment]
看起来工作非常正常啊，那再试试这个，会把图片复制到savepath：
```shell
savepath="/volume1/wallpaper"
pic=$(wget -t 5 --no-check-certificate -qO- "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1")
link=$(echo https://www.bing.com$(echo $pic|sed 's/.\+"url"[:" ]\+//g'|sed 's/".\+//g'))
date=$(echo $pic|sed 's/.\+enddate[": ]\+//g'|grep -Eo 2[0-9]{7}|head -1)
tmpfile=/tmp/$date"_bing.jpg"
touch $savepath/bing.log
wget -t 5 --no-check-certificate $link -O $tmpfile -o $savepath/bing.log
echo $link >>$savepath/bing.log
echo $date >>$savepath/bing.log
echo $tmpfile >>$savepath/bing.log
echo $pic >>$savepath/bing.log
copyright=$(echo $pic|sed 's/.\+"copyright[:" ]\+//g'|sed 's/".\+//g')
cninfo=$(echo $copyright|sed 's/，/"/g'|sed 's/,/"/g'|sed 's/(/"/g'|sed 's/ //g'|sed 's/\//_/g'|sed 's/)//g')
title=$(echo $cninfo|cut -d'"' -f1)
word=$(echo $cninfo|cut -d'"' -f2)
cp -f $tmpfile $savepath/$date@$title-$word.jpg
echo $date@$title-$word.jpg >>$savepath/bing.log
```

**Comment by xxzj990** [comment]
我找到问题了，去掉一个if fi就好了，虽然不懂为啥。。。。修改后如下：

> savepath="/volume1/wallpaper"
pic=$(wget -t 5 --no-check-certificate -qO- "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1")
link=$(echo https://www.bing.com$(echo $pic|sed 's/.\+"url"[:" ]\+//g'|sed 's/".\+//g'))
date=$(echo $pic|sed 's/.\+enddate[": ]\+//g'|grep -Eo 2[0-9]{7}|head -1)
tmpfile=/tmp/$date"_bing.jpg"
wget -t 5 --no-check-certificate  $link -qO $tmpfile
rm -rf /usr/syno/etc/login_background*.jpg
cp -f $tmpfile /usr/syno/etc/login_background.jpg &>/dev/null
cp -f $tmpfile /usr/syno/etc/login_background_hd.jpg &>/dev/null
cp -f $tmpfile /usr/syno/synoman/webman/resources/images/default_wallpaper/01.jpg &>/dev/null
cp -f $tmpfile /usr/syno/synoman/webman/resources/images/default/1x/default_wallpaper/dsm6_01.jpg &>/dev/null
cp -f $tmpfile /usr/syno/synoman/webman/resources/images/default/2x/default_wallpaper/dsm6_01.jpg &>/dev/null
cp -f $tmpfile /usr/syno/synoman/webman/resources/images/default/1x/default_wallpaper/dsm6_02.jpg &>/dev/null
cp -f $tmpfile /usr/syno/synoman/webman/resources/images/default/2x/default_wallpaper/dsm6_02.jpg &>/dev/null
title=$(echo $pic|sed 's/.\+"title":"//g'|sed 's/".\+//g')
copyright=$(echo $pic|sed 's/.\+"copyright[:" ]\+//g'|sed 's/".\+//g')
word=$(echo $copyright|sed 's/(.\+//g')
if  [ ! -n "$title" ];then
cninfo=$(echo $copyright|sed 's/，/"/g'|sed 's/,/"/g'|sed 's/(/"/g'|sed 's/ //g'|sed 's/\//_/g'|sed 's/)//g')
title=$(echo $cninfo|cut -d'"' -f1)
word=$(echo $cninfo|cut -d'"' -f2)
fi
sed -i s/login_background_customize=.*//g /etc/synoinfo.conf
echo "login_background_customize=\"yes\"">>/etc/synoinfo.conf
sed -i s/login_welcome_title=.*//g /etc/synoinfo.conf
echo "login_welcome_title=\"$title\"">>/etc/synoinfo.conf
sed -i s/login_welcome_msg=.*//g /etc/synoinfo.conf
echo "login_welcome_msg=\"$word\"">>/etc/synoinfo.conf
if (echo $savepath|grep -q '/') then
cp -f $tmpfile $savepath/$date@$title-$word.jpg
fi

**Comment by xxzj990** [comment]
![微信截图_20190312110421](https://user-images.githubusercontent.com/5134154/54171789-9d947680-44b6-11e9-976d-9d0711af03ed.png)

**Comment by xxzj990** [comment]
![微信截图_20190312110526](https://user-images.githubusercontent.com/5134154/54171846-c87eca80-44b6-11e9-9660-d3625e07e77b.png)

去掉了这里

**Comment by xxzj990** [comment]
谢谢 @kkkgo

**Comment by kkkgo** [comment]
那就怪了 按逻辑来说如果这个判断出问题脚本应该什么事都不会做才对

**Comment by xxzj990** [comment]
> 那就怪了 按逻辑来说如果这个判断出问题脚本应该什么事都不会做才对

那是不是群晖的bug。。。我现在确实可以了

**Comment by kkkgo** [comment]
试试这个
```shell
#如需收集每日美图去掉下面注释设置保存文件夹路径
#savepath="/volume1/wallpaper"
#在FileStation里面右键文件夹属性可以看到路径
pic=$(wget -t 5 --no-check-certificate -qO- "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1")
echo $pic|grep -q enddate||exit
link=$(echo https://www.bing.com$(echo $pic|sed 's/.\+"url"[:" ]\+//g'|sed 's/".\+//g'))
date=$(echo $pic|sed 's/.\+enddate[": ]\+//g'|grep -Eo 2[0-9]{7}|head -1)
tmpfile=/tmp/$date"_bing.jpg"
wget -t 5 --no-check-certificate  $link -qO $tmpfile
[ -s $tmpfile ]||exit
rm -rf /usr/syno/etc/login_background*.jpg
cp -f $tmpfile /usr/syno/etc/login_background.jpg &>/dev/null
cp -f $tmpfile /usr/syno/etc/login_background_hd.jpg &>/dev/null
cp -f $tmpfile /usr/syno/synoman/webman/resources/images/default_wallpaper/01.jpg &>/dev/null
cp -f $tmpfile /usr/syno/synoman/webman/resources/images/default/1x/default_wallpaper/dsm6_01.jpg &>/dev/null
cp -f $tmpfile /usr/syno/synoman/webman/resources/images/default/2x/default_wallpaper/dsm6_01.jpg &>/dev/null
cp -f $tmpfile /usr/syno/synoman/webman/resources/images/default/1x/default_wallpaper/dsm6_02.jpg &>/dev/null
cp -f $tmpfile /usr/syno/synoman/webman/resources/images/default/2x/default_wallpaper/dsm6_02.jpg &>/dev/null
title=$(echo $pic|sed 's/.\+"title":"//g'|sed 's/".\+//g')
copyright=$(echo $pic|sed 's/.\+"copyright[:" ]\+//g'|sed 's/".\+//g')
word=$(echo $copyright|sed 's/(.\+//g')
if  [ ! -n "$title" ];then
cninfo=$(echo $copyright|sed 's/，/"/g'|sed 's/,/"/g'|sed 's/(/"/g'|sed 's/ //g'|sed 's/\//_/g'|sed 's/)//g')
title=$(echo $cninfo|cut -d'"' -f1)
word=$(echo $cninfo|cut -d'"' -f2)
fi
sed -i s/login_background_customize=.*//g /etc/synoinfo.conf
echo "login_background_customize=\"yes\"">>/etc/synoinfo.conf
sed -i s/login_welcome_title=.*//g /etc/synoinfo.conf
echo "login_welcome_title=\"$title\"">>/etc/synoinfo.conf
sed -i s/login_welcome_msg=.*//g /etc/synoinfo.conf
echo "login_welcome_msg=\"$word\"">>/etc/synoinfo.conf
if (echo $savepath|grep -q '/') then
cp -f $tmpfile $savepath/$date@$title-$word.jpg
fi
rm -rf /tmp/*_bing.jpg
```
